behaviors:  
  TicTacToeBehaviourSAC:
    trainer_type: sac
    hyperparameters:
      #PPO/SAC hyperparameters:
      batch_size: 256
      buffer_size: 2048
      learning_rate: 1e-5
      learning_rate_schedule: linear      
      #SAC specific hyperparameters:
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 10.0
      save_replay_buffer: false
      init_entcoef: 0.5
      reward_signal_steps_per_update: 10.0
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 32
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 1e9
    time_horizon: 64
    summary_freq: 20000
    threaded: true
    self_play:
      save_steps: 5000
      team_change: 10000
      swap_steps: 2000
      window: 10

  TicTacToeBehaviourPPO:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 4096
      beta: 1e-2
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      learning_rate: 3e-4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 32
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 10000
    max_steps: 1e9
    time_horizon: 64
    summary_freq: 20000
    threaded: true
    self_play:
      save_steps: 5000
      team_change: 10000
      swap_steps: 2000
      window: 10

  TicTacToeEvaluatorBehaviourPPO:
    trainer_type:  ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      beta: 1e-2
      epsilon: 0.3
      lambd: 0.95
      num_epoch: 5
      learning_rate: 3e-4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 32
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 5000
    max_steps: 1e9
    time_horizon: 64
    summary_freq: 10000
    threaded: true